- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup


    - name: Create cloudtech vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        tenancy: default
        dns_support: yes
        dns_hostnames: yes
        state: "{{state}}"
      register: vpcout

 #   - debug:
 #       var: vpcout

    - name: create public subnet 1 in AZ-1
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone1}}"
        cidr: "{{PubSub1Cidr}}"
        region: "{{region}}"
        map_public: yes
        tags:
          Name: vprofile-pubsub1
      register: pubsub1_out



    - name: create public subnet 2 in AZ-2
      ec2_vpc_subnet:
          state: "{{state}}"
          vpc_id: "{{vpcout.vpc.id}}"
          az: "{{zone2}}"
          cidr: "{{PubSub2Cidr}}"
          region: "{{region}}"
          map_public: yes
          tags:
            Name: vprofile-pubsub2
      register: pubsub2_out



    - name: create public subnet 3 in AZ-3
      ec2_vpc_subnet:
          state: "{{state}}"
          vpc_id: "{{vpcout.vpc.id}}"
          az: "{{zone3}}"
          cidr: "{{PubSub3Cidr}}"
          region: "{{region}}"
          map_public: yes
          tags:
            Name: vprofile-pubsub3
      register: pubsub3_out


    - name: create private subnet 1 in AZ-1
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone1}}"
        cidr: "{{PriSub1Cidr}}"
        region: "{{region}}"
        map_public: no
        tags:
          Name: vprofile-prisub1
      register: prisub1_out

    - name: create private subnet 2 in AZ-2
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone2}}"
        cidr: "{{PriSub2Cidr}}"
        region: "{{region}}"
        map_public: no
        tags:
          Name: vprofile-prisub2
      register: prisub2_out

    - name: create private subnet 3 in AZ-3
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone3}}"
        cidr: "{{PriSub3Cidr}}"
        region: "{{region}}"
        map_public: no
        tags:
          Name: vprofile-prisub3
      register: prisub3_out

    - debug:
        var: prisub3_out

    - name: create Internet Gateway
      ec2_vpc_igw:
        region: "{{region}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        tags:
          Name: vprofile_IGW
      register: igw_out

    - debug:
       var: igw_out

    - name: create public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        subnets:
          - "{{pubsub1_out.subnet.id}}"
          - "{{pubsub2_out.subnet.id}}"
          - "{{pubsub3_out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igw_out.gateway_id}}"
        tags:
          Name: vprofile-pubRouteTable
      register: pubRT_out


    - name: Create NAT Gateway for pvt subnets
      ec2_vpc_nat_gateway:
#        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        subnet_id: "{{pubsub1_out.subnet.id}}"
        wait: yes
#        tags:
#          Name: natGTW
        if_exist_do_not_create: true
      register: natgtw_out

    - name: setup Private Subnet Route table
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        subnets:
         - "{{prisub1_out.subnet.id}}"
         - "{{prisub2_out.subnet.id}}"
         - "{{prisub3_out.subnet.id}}"
        routes:
         - dest: 0.0.0.0/0
           gateway_id: "{{natgtw_out.nat_gateway_id}}"
        tags:
          Name: vprofile-priRouteTable
      register: priRT_out

    - debug:
        var: "{{item}}"
      loop:
        - vpcout.vpc.id
        - pubsub1_out.subnet.id
        - pubsub2_out.subnet.id
        - pubsub3_out.subnet.id
        - prisub1_out.subnet.id
        - prisub2_out.subnet.id
        - prisub3_out.subnet.id
        - igw_out.gateway_id
        - natgtw_out.nat_gateway_id
        - priRT_out.route_table.id
        - pubRT_out.route_table.id
