- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup


    - name: Create cloudtech vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        tenancy: default
        dns_support: yes
        dns_hostnames: yes
        state: "{{state}}"
      register: vpcout

 #   - debug:
 #       var: vpcout

    - name: create public subnet 1 in AZ-1
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone1}}"
        cidr: "{{PubSub1Cidr}}"
        region: "{{region}}"
        map_public: yes
        tags:
          Name: vprofile-pubsub1
      register: pubsub1_out



    - name: create public subnet 2 in AZ-2
      ec2_vpc_subnet:
          state: "{{state}}"
          vpc_id: "{{vpcout.vpc.id}}"
          az: "{{zone2}}"
          cidr: "{{PubSub2Cidr}}"
          region: "{{region}}"
          map_public: yes
          tags:
            Name: vprofile-pubsub2
      register: pubsub2_out



    - name: create public subnet 3 in AZ-3
      ec2_vpc_subnet:
          state: "{{state}}"
          vpc_id: "{{vpcout.vpc.id}}"
          az: "{{zone3}}"
          cidr: "{{PubSub3Cidr}}"
          region: "{{region}}"
          map_public: yes
          tags:
            Name: vprofile-pubsub3
      register: pubsub3_out







